#!/usr/bin/env bash

set -e
set -u
set -o pipefail

VERSION="v0.1.0"
PROGRAM="${0##*/}"
COMMAND="${1:-usage}"
UPSTREAM=master

GETOPT=$(command -v gnu-getopt || command -v getopt)
PR_TEMPLATE="$(cat <<-EOF
{title}

# Summary
{summary}

## Reviewers:

## Labels:
EOF
)"

main(){
	case $COMMAND in
		""|"-h"|"--help"|"help"|"usage") usage; exit 0;;
		"-v"|"--version") cmd_version; exit 0;;
	esac

	! type "cmd_$COMMAND" > /dev/null && usage

	shift;
	"cmd_$COMMAND" "$@"
}

usage() {
	topic="${1:-}"
	case $topic in

		"" ) cat <<-EOF
		pr <command> [<args>]

		Commands
		--------

		* pr sync
			Create or update a github pull request from a local branch

		* pr merge
			Merge a branch for a github pull request which has been approveed

		* pr approve [--nopush] [--tag-only]
			Approve a github pull request and create review tag

		* pr show [--noheader]
			Show review tags for the current HEAD

		* pr verify
			Verify that the current HEAD has at least the minimum number of valid review tags

		* pr version
			Print the current version
		EOF
		;;

	"sync" ) cat <<-EOF
		pr sync

		Create or update a github pull request from a local branch
		EOF
		;;

	"approve" ) cat <<-EOF
		pr approve <pr number> [--nopush] [--tag-only]

		Approve a github pull request and create review tag

		--nopush: Do not push review tag to remote repo
		--tag-only: Do not approve pull request on github and only create review tag.
			Review tag will still be pushed to remote repo unless --nopush is given.
		EOF
		;;

	"merge" ) cat <<-EOF
		pr merge

		Merge branch for a github pull request which has been approveed.

		The branch to merge must be the currently checked out branch.
		EOF
		;;

	"show" ) cat <<-EOF
		pr show [--noheader]

		Show review tags for the current HEAD

			--noheader: Do not output header containing number of valid review tags
		EOF
		;;

	"verify" ) cat <<-EOF
		pr verify [--min-count 1]

		Verify that the current HEAD has at least a minimum number of valid review tags

			--min-count: Minimum number of valid review tags required for verification (Default 1).
		EOF
		;;

	"version" ) cat <<-EOF
		pr version

		Print current version
		EOF
		;;

	esac
}

mark_pr_approveed() {
	COMMIT="$1"
	URL="$2"
	USER="$(grep user "$HOME/.config/hub" | cut -d' ' -f3)"
	TOKEN="$(grep token "$HOME/.config/hub" | cut -d' ' -f4)"
	PR_URL="$(sed -E 's/pull\/([0-9]+)/pulls\/\1\/reviews/ ; s/github\.com/api\.github\.com\/repos/' <<< "$URL")"
  # shellcheck disable=2016
	BODY="$(printf '{"commit_id": "%s", "event": "APPROVE", "body": "Approveed via `%s %s`"}' "$COMMIT" "$PROGRAM" "$VERSION")"

	if ! RESULT="$(curl -sfS \
	-H "Authorization: Bearer $TOKEN" \
	-H "Content-Type: application/json" \
	-H "Approve: application/json" \
	--data "$BODY" \
	"$PR_URL" 2>&1)"; then
		if echo "$RESULT" | grep '422 Unprocessable Entity' >/dev/null 2>&1; then
			printf "\\nerror: unable to approve own pull request\\n"
			exit 1
		fi
		printf "\\nEncountered error from github while attempting to mark pr approveed:\\n%s\\n" "$RESULT"
	else
		echo "OK"
	fi
}

cmd_approve() {
	local opts push=1 approve=1
	opts="$($GETOPT -o hnt -l help,nopush,tagonly -n "$PROGRAM" -- "$@")";
	eval set -- "$opts"
	while true; do case $1 in
		-h|--help) usage add; exit 0 ;;
		-n|--nopush) push=0; shift ;;
		-t|--tagonly) approve=0; shift ;;
		--) shift; break ;;
	esac done
	[ "$#" != 1 ] && usage approve && exit 1

	pr=${1}
	if [[ ! "$pr" =~ ^[0-9]+$ ]]; then
		echo "invalid pull request number: $pr"
		exit 1
	fi

	PR_INFO="$(hub pr list -h "$(git rev-parse --abbrev-ref HEAD)" -f '%H %U' -s open -L 1)"
	BRANCH="$(cut -d' ' -f1 <<< "$PR_INFO")"
	URL="$(cut -d' ' -f2 <<< "$PR_INFO")"
	COMMIT="$(git rev-parse "$BRANCH")"
	REVIEWER_EMAIL="$(git config user.email)"
	TAG_NAME="reviews/$REVIEWER_EMAIL-$(git rev-parse --short HEAD)"

	# check for existing review tag on this commit
	if git rev-parse "refs/tags/$TAG_NAME^{tag}" > /dev/null 2>&1; then
		echo "Error: Review tag $TAG_NAME already exists for commit $(git rev-parse --short "$COMMIT")"
		exit 1
	fi

	[[ "$approve" == "0" ]] || { echo -n "Marking pull request $pr as approveed..."; mark_pr_approveed "$COMMIT" "$URL"; echo "OK"; }

	echo -n "Checking out pull request $pr..."
	if r="$(hub pr checkout "$pr")"; then
		echo "OK"
	else
		echo "Error: checkout failed"
		echo "$r"
		exit 1
	fi

	echo -n "Fetching pull request $pr head branch $BRANCH..."
	git fetch origin "$BRANCH" > /dev/null 2>&1
	echo "OK"

	echo -n "Creating review tag..."
	git tag --sign -m "Changes on this branch were reviewed and approveed by the creator of this tag" "$TAG_NAME" "$COMMIT"
	echo "OK"

	[[ "$push" == "0" ]] || { echo -n "Pushing review tag to origin..."; git push origin "$TAG_NAME" > /dev/null 2>&1; echo "OK"; }
}

cmd_show() {
	local opts header=1
	opts="$($GETOPT -o hn -l help,noheader -n "$PROGRAM" -- "$@")";
	eval set -- "$opts"
	while true; do case $1 in
		-h|--help) usage show; exit 0;;
		-n|--noheader) header=0; shift;;
		--) shift; break;;
	esac done
	[ "$#" -gt 1 ] && usage show && exit 1

	COMMIT="$(git rev-parse HEAD)"
	FORMAT_SCRIPT="%(if:notequals=<$(git config user.email)>)%(taggeremail)%(then)%(taggeremail): Valid Review Tag%(end)"

	valid_signed_tags="$(git for-each-ref \
		--points-at "$COMMIT" \
		--format "$FORMAT_SCRIPT" \
		refs/tags/reviews \
	)"
	if ! valid_count="$(grep -c "Valid Review Tag" <<< "$valid_signed_tags")"; then
		valid_count=0
	fi
	[[ "$header" != 0 ]] && printf "$valid_count valid review tag(s) for commit %s\\n" "$COMMIT"
	[[ -n "$valid_signed_tags" ]] && echo "$valid_signed_tags"
}

update_pr() {
	BRANCH_NAME="$1"
	# already have a pr for this branch open
	echo "Branch $BRANCH_NAME already has one or more open pull requests"

	# is the local copy of the remote ref up to date?
	LOCAL_COMMIT_COUNT="$(git rev-list --count "$BRANCH_NAME")"
	REMOTE_COMMIT_COUNT="$(git rev-list --count "origin/$BRANCH_NAME")"
	COMMIT_DELTA=$(("$LOCAL_COMMIT_COUNT" - "$REMOTE_COMMIT_COUNT"))

	if [ "$COMMIT_DELTA" == "0" ]; then
		echo "Remote branch origin/$BRANCH_NAME is up to date, aborting"
		exit 1
	fi

	read -r -p "Would you like to update pull request #$PR_NUMBER? [y/N] " should_update

	if [[ "$should_update" =~ ^[yY]$ ]]; then
		echo "Updating pull request #$PR_NUMBER... "
		git push origin "$(git rev-parse --abbrev-ref HEAD)"
	else
		echo "Aborted: Pull request not updated"
		exit 1
	fi
}

create_pr() {
	BRANCH_NAME="$1"
	echo "Creating new PR for branch $BRANCH_NAME..."

	PR_MESSAGE_FILE=$(mktemp)
	HEAD_COMMIT_SUBJECT="$(git log --pretty='format:%s' -1)"
	HEAD_COMMIT_BODY="$(git log --pretty='format:%b' -1)"

	# replace PR template placeholders with actual data
	sed -e "s/{title}/${HEAD_COMMIT_SUBJECT:-''}/" -e "s/{summary}/${HEAD_COMMIT_BODY:-''}/" <<< "$PR_TEMPLATE" > "$PR_MESSAGE_FILE"
	${EDITOR:-vi} "$PR_MESSAGE_FILE"

	# extract reviewers, labels, and assignees
	if grep "Reviewers:" "$PR_MESSAGE_FILE" > /dev/null; then
		REVIEWERS="$(grep "Reviewers:" "$PR_MESSAGE_FILE" | cut -d':' -f2 | tr -d ' ')"
	fi

	if grep "Labels:" "$PR_MESSAGE_FILE" > /dev/null; then
		LABELS="$(grep "Labels:" "$PR_MESSAGE_FILE" | cut -d':' -f2 | tr -d ' ')"
	fi

	# if grep "Assignees:" "$PR_MESSAGE_FILE" > /dev/null; then
	# 	ASSIGNEES="$(grep "Assignees:" "$PR_MESSAGE_FILE" | cut -d':' -f2 | tr -d ' ')"
	# fi

	PR_CREATE_ARGS="-F $PR_MESSAGE_FILE -p"
	[ ! -z "$REVIEWERS" ] && PR_CREATE_ARGS="$PR_CREATE_ARGS -r $REVIEWERS"
	[ ! -z "$LABELS" ] && PR_CREATE_ARGS="$PR_CREATE_ARGS -l $LABELS"
	# [ ! -z "$ASSIGNEES" ] && PR_CREATE_ARGS="$PR_CREATE_ARGS -a $ASSIGNEES"

	# make sure all local commits are pushed up to origin
	if [ "$(git rev-parse "origin/$BRANCH_NAME" 2>&1 >/dev/null)" != "$(git rev-parse "$BRANCH_NAME")" ]; then
		echo "Updating out of date remote branch origin/$BRANCH_NAME..."
		git push origin "$BRANCH_NAME" > /dev/null 2>&1
	fi

	# shellcheck disable=SC2086
	PR_URL="$(hub pull-request $PR_CREATE_ARGS 2>&1 | grep 'https://' )"
	echo "Pull request successfully created: $PR_URL"
}

cmd_sync() {
	[ "$#" -eq 0 ] || { usage sync; exit 1; }

	BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
	[ "$BRANCH_NAME" == "$UPSTREAM" ] && echo "Error: Cannot create pull request with commits made directly on local copy of upstream branch $UPSTREAM" && exit 1
	PR_NUMBER="$(hub pr list -h "$BRANCH_NAME" -s open -f '%I' -L 1 2> /dev/null || echo -n 0)"

	# check for existing open pr for this branch
	if [ "${PR_NUMBER:-0}" -ge 1 ]; then
		update_pr "$BRANCH_NAME"
		exit 0
	fi

	echo "No open pull request found for local branch $BRANCH_NAME"
	read -r -p "Create a new pull request? [Y/n] " should_create

	if [[ "$should_create" =~ ^[Yy]$ || "$should_create" == '' ]]; then
		create_pr "$BRANCH_NAME"
	else
		echo "Aborted: pull request not created"
		exit 0
	fi
}

merge_pr() {
	BRANCH_NAME="$1"
	PR_NUMBER="$2"

	echo "Merging branch $BRANCH_NAME (pull request #$PR_NUMBER) into branch $UPSTREAM..."
	git checkout "$UPSTREAM"
	git pull origin "$UPSTREAM" # 1 tap
	git merge --no-ff "$BRANCH_NAME"
	git push origin "$UPSTREAM" ":$BRANCH_NAME" # 3 tap
	git branch -D "$BRANCH_NAME"
}

cmd_merge() {
	BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
	PR_NUMBER="$(hub pr list -h "$BRANCH_NAME" -s open -f '%I' -L 1)"

	if [[ "$PR_NUMBER" == "" ]]; then
		echo "Failed to find open pull request for branch $BRANCH_NAME"
		exit 1
	fi

	# shellcheck disable=SC2119
	cmd_verify && merge_pr "$BRANCH_NAME" "$PR_NUMBER"
}

# shellcheck disable=SC2120
cmd_verify() {
	local opts min_count=1
	opts="$($GETOPT -o hm: -l help,min-count: -n "$PROGRAM" -- "$@")";
	eval set -- "$opts"
	while true; do case $1 in
		-h|--help) usage verify; exit 0;;
		-m|--min-count) min_count="$2"; shift 2 ;;
		--) shift; break ;;
	esac done
	[ "$#" -gt 0 ] && usage verify && exit 1
	# make sure tip of merged branch has at least the minimum number of signed review tags
	local valid_signed_tags=0
	BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
	FORMAT_SCRIPT="%(if:notequals=<$(git config user.email)>)%(taggeremail)%(then)v%(end)"
	valid_signed_tags=$(git for-each-ref \
		--points-at "$BRANCH_NAME" \
		--format "$FORMAT_SCRIPT" \
		refs/tags/reviews | grep -c v || true \
	)

	if [[ "$valid_signed_tags" -lt "$min_count" ]]; then
		echo "Error: Failed to find enough signed review tags to satisfy minimum review requirement."
		echo "Error: $valid_signed_tags reviews were found, but $min_count are required"
		exit 1
	fi
}

cmd_version() {
	echo "$PROGRAM $VERSION"
}

main "$@"
